/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
  // on Android, a nasty hack is needed: {"resizeClear": true}

  // you can add a canvas by it's ID...
  skycons.add("icon0", Skycons.RAIN);
  skycons.add("icon1", Skycons.CLEAR_DAY);
  skycons.add("icon2", Skycons.CLOUDY);
  skycons.add("icon3", Skycons.RAIN);

  // start animation!
  skycons.play();
  
  // want to change the icon? no problem:
  // skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
  
/*
Get value from Bootstrap dropdown menu
*/

  $(document).ready(function () {
      $.ajax('https://query.yahooapis.com/v1/public/yql', {
        method: 'GET',
        data: {
          q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="Taipei")',
          format: 'json'
        },
        success: function (data) {
		 var weatherInfo = data.query.results.channel;
            // var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
		 console.log(weatherInfo);
            $('.temperature').text(((weatherInfo.item.condition.temp-32)*5/9).toFixed(1));
            $('.condition').text(weatherInfo.item.forecast[0].date);
		 $('.date1').text(weatherInfo.item.forecast[1].date);
		 $('.date2').text(weatherInfo.item.forecast[2].date);
		 $('.date3').text(weatherInfo.item.forecast[3].date);
		 $('.date1tem').text(((weatherInfo.item.forecast[1].low-32)*5/9).toFixed(0)+'-'+((weatherInfo.item.forecast[3].high-32)*5/9).toFixed(0));
		 $('.date2tem').text(((weatherInfo.item.forecast[2].low-32)*5/9).toFixed(0)+'-'+((weatherInfo.item.forecast[3].high-32)*5/9).toFixed(0));
		 $('.date3tem').text(((weatherInfo.item.forecast[3].low-32)*5/9).toFixed(0)+'-'+((weatherInfo.item.forecast[3].high-32)*5/9).toFixed(0));		 
        }
      });

  });




   
$('#dropdown li').on('click', function(){
    //alert($(this).text());
	$('.dropdown-toggle').html($(this).text()+'  <span class="caret"></span>');
	var city=$(this).text();
	       $.ajax('https://query.yahooapis.com/v1/public/yql', {
	         method: 'GET',
	         data: {
	           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
	           format: 'json'
	         },
	         success: function (data) {
				 var weatherInfo = data.query.results.channel;
	             // var cityMatch = 'It seems ' + weatherInfo.item.condition.text.toLowerCase()+' in '+ weatherInfo.location.city + ', ' + weatherInfo.location.country
				 console.log(weatherInfo);
	             $('.temperature').text(((weatherInfo.item.condition.temp-32)*5/9).toFixed(1));
	             $('.condition').text(weatherInfo.item.forecast[0].date);
				 $('.date1').text(weatherInfo.item.forecast[1].date);
				 $('.date2').text(weatherInfo.item.forecast[2].date);
				 $('.date3').text(weatherInfo.item.forecast[3].date);
				 $('.date1tem').text(((weatherInfo.item.forecast[1].low-32)*5/9).toFixed(0)+'-'+((weatherInfo.item.forecast[3].high-32)*5/9).toFixed(0));
				 $('.date2tem').text(((weatherInfo.item.forecast[2].low-32)*5/9).toFixed(0)+'-'+((weatherInfo.item.forecast[3].high-32)*5/9).toFixed(0));
				 $('.date3tem').text(((weatherInfo.item.forecast[3].low-32)*5/9).toFixed(0)+'-'+((weatherInfo.item.forecast[3].high-32)*5/9).toFixed(0));
				 for (i = 0; i < 4; i++){ 
				  if(weatherInfo.item.forecast[i].text==="Heavy Rain"||weatherInfo.item.forecast[i].text==="Rain"){
				 	  skycons.set("icon"+i,Skycons.SLEET);
				  }else if(weatherInfo.item.forecast[i].text==="PM Thunderstorms"||weatherInfo.item.forecast[i].text==="Heavy Thunderstorms"||weatherInfo.item.forecast[i].text==="Thunderstorms"||weatherInfo.item.forecast[i].text==="Thundershowers/Wind"||weatherInfo.item.forecast[i].text==="Showers"||weatherInfo.item.forecast[i].text==="AM Showers"){
				 	  skycons.set("icon"+i,Skycons.RAIN);
				  }else if(weatherInfo.item.forecast[i].text==="Clear"||weatherInfo.item.forecast[i].text==="Sunny"){
				 	  skycons.set("icon"+i,Skycons.CLEAR_DAY);
				  }if(weatherInfo.item.forecast[i].text==="Partly Cloudy"||weatherInfo.item.forecast[i].text==="AM Clouds/PM Sun"){
				 	  skycons.set("icon"+i,Skycons.CLOUDY);
				  }
			     }
				 skycons.play();
	         }
	       });
});

